# Generated by Django 3.2.8 on 2022-08-18 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.ImageField(upload_to='picture/')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('about', models.TextField()),
                ('url', models.URLField()),
                ('contact', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dep', models.ForeignKey(default='Empty', on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='home.departement')),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac', to='home.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='home.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='faculte',
            name='univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universite', to='home.universite'),
        ),
        migrations.AddField(
            model_name='departement',
            name='fac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculte', to='home.faculte'),
        ),
    ]
